x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  traefik:
    image: traefik:${TRAEFIK_TAG}
    restart: "unless-stopped"
    command:
#      - --accesslog=true
#      - --accesslog.format=json
#      - --accesslog.fields.defaultmode=keep
#      - --accesslog.fields.headers.defaultmode=keep
#      - --certificatesResolvers.letsencrypt.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory
      - --log.level=${LOG_LEVEL:-info}
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --certificatesresolvers.letsencrypt.acme.dnschallenge=true
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL}
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      - --entrypoints.web.address=:${TRAEFIK_WEB_HTTP_PORT}
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.websecure.address=:${TRAEFIK_WEB_PORT}
      - --metrics
      - --metrics.prometheus
      - --global.sendAnonymousUsage
    ports:
      - ${HOST_IP:-}:${TRAEFIK_WEB_PORT}:${TRAEFIK_WEB_PORT}/tcp
      - ${HOST_IP:-}:${TRAEFIK_WEB_HTTP_PORT}:${TRAEFIK_WEB_HTTP_PORT}/tcp
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
      - CF_ZONE_API_TOKEN=${CF_ZONE_API_TOKEN:-}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/letsencrypt
      - /etc/localtime:/etc/localtime:ro
    labels:
      - metrics.scrape=true
      - metrics.path=/metrics
      - metrics.port=8080
      - metrics.instance=traefik
    <<: *logging

  cf-ddns:
    image: ghcr.io/joshuaavalon/cloudflare-ddns:${DDNS_TAG}
    restart: "unless-stopped"
    environment:
      - CF_DNS__LOG_LEVEL=${LOG_LEVEL:-info}
      - CF_DNS__AUTH__SCOPED_TOKEN=${CF_DNS_API_TOKEN}
      - CF_DNS__DOMAINS_0__ZONE_NAME=${DOMAIN}
      - CF_DNS__DOMAINS_0__ZONE_ID=${CF_ZONE_ID:-}
      - CF_DNS__DOMAINS_0__NAME=${DDNS_SUBDOMAIN}.${DOMAIN}
      - CF_DNS__DOMAINS_0__PROXIED=${DDNS_PROXY}
      - CF_DNS__DOMAINS_0__CREATE=true
      - CF_DNS__DOMAINS_0__TYPE=A
      - CF_DNS__DOMAINS_1__ZONE_NAME=${DOMAIN}
      - CF_DNS__DOMAINS_1__ZONE_ID=${CF_ZONE_ID:-}
      - CF_DNS__DOMAINS_1__NAME=${DDNS_SUBDOMAIN}.${DOMAIN}
      - CF_DNS__DOMAINS_1__PROXIED=${DDNS_PROXY}
      - CF_DNS__DOMAINS_1__CREATE=true
      - CF_DNS__DOMAINS_1__TYPE=AAAA
    volumes:
      - /etc/localtime:/etc/localtime:ro
    <<: *logging

volumes:
  certs:
