  - job_name: 'validator'
    scrape_interval: 5s
    static_configs:
      - targets: ['validator:8009']
  - job_name: 'consensus node'
    scrape_interval: 5s
    static_configs:
      - targets: ['consensus:8008']
