name: docker-compose-actions-workflow

on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  test-teku-besu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: khan/pull-request-comment-trigger@v1.1.0
        id: check
        with:
          trigger: '/test-teku'
          trigger: '/test-besu'
          trigger: '/test-all'
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - name: Create .env file
        run: |
          cp default.env .env
      - name: Set Teku/Besu
        run: |
          source ./.github/helper.sh
          COMPOSE_FILE=teku.yml:besu.yml
          var=COMPOSE_FILE
          set_value_in_env
      - name: Start Teku/Besu
        run: |
          ./ethd up
      - name: Test Teku
        run: |
          ./.github/check-service.sh consensus
      - name: Test Besu
        run: |
          ./.github/check-service.sh execution
      - name: Set Teku/Besu w/ VC
        run: |
          source ./.github/helper.sh
          COMPOSE_FILE=teku-cl-only.yml:teku-vc-only.yml:besu.yml
          var=COMPOSE_FILE
          set_value_in_env
      - name: Start Teku/Besu
        run: |
          ./ethd up
      - name: Test Teku CL
        run: |
          ./.github/check-service.sh consensus
      - name: Test Teku VC
        run: |
          ./.github/check-service.sh validator
      - name: Test Besu
        run: |
          ./.github/check-service.sh execution
